# Generated by Django 2.2.14 on 2020-07-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='Atalho'),
        ),
    ]
